import type { Metadata } from "next";
import "./globals.css";
import { Spin } from "antd";
import HeaderWrapper from "@/components/layout/header/HeaderWrapper";

export const metadata: Metadata = {
  title: "Next Chapter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (!children) return <Spin fullscreen />;

  return (
    <html lang="en">
      <body className="h-full w-full flex flex-col items-center justify-between">
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <HeaderWrapper />

        <main>{children}</main>
      </body>
    </html>
  );
}
